---

- hosts: all
  become: yes
  pre_tasks:

  - name: update & upgrade server
    apt: 
      update_cache: yes
      upgrade: yes

  - name: set cron job to check uptime of the server every 12 am
    cron:
      name: set cron job to check uptime of the server every 12 am
      minute: "0"
      hour: "0"
      day: "*"
      month: "*"
      weekday: "*"
      job: "/usr/bin/uptime > /var/log/uptime_check.log 2>&1"
      state: present

  - name: clone installation bash script from master vagrant
    copy:
      src: slave_laravel.sh
      dest: ~/
      owner: root
      group: root
      mode: 0744

  - name: Set Execute Permissions on the Script
    command: chmod +x ~/slave_laravel.sh

  - name: Run Bash Script
    command: bash slave_laravel.sh gbenga password@123 < /dev/null
